import { MESSAGES } from "./i18n.js";

export const WEB_CLIENT = `
const MESSAGES=${JSON.stringify(MESSAGES)};
const byId=(id)=>document.getElementById(id);
let locale=(localStorage.getItem("sigma-language")==="en")?"en":"zh-CN";
if(!localStorage.getItem("sigma-language")&&String(navigator.language||"").toLowerCase().startsWith("en"))locale="en";
const t=(key,vars)=>{let text=MESSAGES[locale][key];if(text==null)text=MESSAGES["zh-CN"][key];if(text==null)return key;if(vars)for(const[k,v]of Object.entries(vars))text=text.split("{"+k+"}").join(String(v));return text};
function hydrate(){document.documentElement.lang=locale==="en"?"en":"zh-CN";document.querySelectorAll("[data-i18n]").forEach((node)=>{node.textContent=t(node.dataset.i18n)});document.querySelectorAll("[data-i18n-ph]").forEach((node)=>{node.placeholder=t(node.dataset.i18nPh)});document.querySelectorAll("[data-i18n-title]").forEach((node)=>{node.setAttribute("title",t(node.dataset.i18nTitle))});const toggle=byId("language-toggle");if(toggle)toggle.textContent=locale==="en"?"中文":"English"}
byId("language-toggle").addEventListener("click",()=>{localStorage.setItem("sigma-language",locale==="en"?"zh":"en");location.reload()});
hydrate();
const escapeHtml=(value)=>String(value??"").replace(/[&<>"']/g,(char)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
function toast(message,error){const node=byId("toast");node.textContent=message;node.className="toast show"+(error?" err":"");setTimeout(()=>node.className="toast"+(error?" err":""),2600)}
function busy(button,on,label){if(!button)return;if(on){button.dataset.label=button.textContent;button.textContent=label||t("busy.working");button.disabled=true;return}if(button.dataset.label){button.textContent=button.dataset.label;delete button.dataset.label}button.disabled=false}
async function json(url,options){const response=await fetch(url,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||data.detail||("HTTP "+response.status));return data}
function showPage(name){document.querySelectorAll(".page").forEach((node)=>node.classList.toggle("active",node.id==="page-"+name));document.querySelectorAll(".nav button").forEach((node)=>node.classList.toggle("active",node.dataset.page===name));if(name==="sessions")loadSessions();if(name==="upstream"){loadUpstream();loadOverrides()}}
document.querySelectorAll(".nav button").forEach((button)=>button.addEventListener("click",()=>showPage(button.dataset.page)));
async function loadConfig(){const data=await json("/__bili/config");if(data.parseError)toast(String(data.parseError),true);byId("providers-json").value=JSON.stringify(data.providers||{},null,2);byId("proxy-url").value=data.upstreamProxy||"";byId("compress-json").value=data.compress?JSON.stringify(data.compress,null,2):"";document.querySelectorAll('input[name="proxy-mode"]').forEach((input)=>input.checked=input.value===(data.upstreamProxyMode||"direct"));const pt=data.passthrough||{enabled:false};const banner=byId("passthrough-banner");if(banner){if(pt.enabled){banner.hidden=false;byId("passthrough-source").textContent=pt.source==="env"?t("pt.source_env"):t("pt.source_config");const btn=byId("clear-passthrough");btn.disabled=pt.source==="env";btn.title=pt.source==="env"?t("pt.clear_title"):""}else{banner.hidden=true}}return data}
async function loadUpstream(){try{const data=await json("/__bili/upstream");const labels={"provider":t("src.provider"),"provider-direct":t("src.provider_direct"),"sigma-env":"SIGMA_UPSTREAM_PROXY","web-manual":t("src.web_manual"),"config":t("src.config"),"HTTPS_PROXY":"HTTPS_PROXY","HTTP_PROXY":"HTTP_PROXY","ALL_PROXY":"ALL_PROXY","windows-system":t("src.windows_system"),"windows-bypass":t("src.windows_bypass"),"no-proxy":"NO_PROXY","direct":t("upstream.direct")};byId("upstream-source").textContent=labels[data.source]||data.source||t("upstream.direct");byId("upstream-effective").textContent=data.proxy||"direct";byId("upstream-pac").textContent=data.autoConfigUrl||"—";const state=byId("upstream-state");state.className="status "+(data.connected===true?"ok":data.connected===false?"err":"");state.textContent=data.connected===true?t("upstream.connected"):data.connected===false?(data.error||t("upstream.failed")):t("upstream.never_seen")}catch(error){byId("upstream-state").textContent=String(error)}}
async function saveUpstream(){const button=byId("save-upstream");busy(button,true,t("busy.saving"));const mode=document.querySelector('input[name="proxy-mode"]:checked').value;try{await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({upstreamProxyMode:mode,upstreamProxy:byId("proxy-url").value.trim()||null})});toast(t("toast.upstream_saved"));await loadUpstream()}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function testUpstream(){const button=byId("test-upstream");busy(button,true,t("busy.testing"));try{const data=await json("/__bili/upstream/test",{method:"POST"});toast(t("toast.connect_ok",{status:data.status}));await loadUpstream()}catch(error){toast(String(error),true);await loadUpstream()}finally{busy(button,false)}}
async function saveProviders(){const button=byId("save-providers");busy(button,true,t("busy.saving"));try{const providers=JSON.parse(byId("providers-json").value);await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({providers})});await json("/__bili/config/reload",{method:"POST"});toast(t("toast.providers_saved"))}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function saveCompress(){const button=byId("save-compress");busy(button,true,t("busy.saving"));try{const text=byId("compress-json").value.trim();const compress=text?JSON.parse(text):null;await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({compress})});toast(t("toast.compress_saved"))}catch(error){toast(String(error),true)}finally{busy(button,false)}}
async function loadOverrides(){try{const data=await loadConfig();const providers=data.providers||{};const box=byId("upstream-overrides");const entries=Object.entries(providers);if(entries.length===0){box.innerHTML='<p class="status">'+t("overrides.empty")+'</p>';return}box.innerHTML='<table><thead><tr><th>Provider URL</th><th>'+t("overrides.th_proxy")+'</th></tr></thead><tbody>'+entries.map(([url,route])=>'<tr><td class="mono">'+escapeHtml(url)+'</td><td><input class="mono override-proxy" data-url="'+escapeHtml(url)+'" value="'+escapeHtml((route&&route.proxy)||"")+'" placeholder="'+t("overrides.inherit")+'"></td></tr>').join("")+'</tbody></table>'}catch(error){byId("upstream-overrides").textContent=String(error)}}
async function saveOverrides(){const button=byId("save-overrides");busy(button,true,t("busy.saving"));try{const data=await loadConfig();const providers=data.providers||{};document.querySelectorAll(".override-proxy").forEach((input)=>{const url=input.dataset.url;if(!url)return;if(!providers[url])providers[url]={};const val=input.value.trim();if(val)providers[url].proxy=val;else delete providers[url].proxy});await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({providers})});await json("/__bili/config/reload",{method:"POST"});toast(t("toast.overrides_saved"));await loadOverrides()}catch(error){toast(String(error),true)}finally{busy(button,false)}}
const fmtW=(n)=>(typeof n==="number"&&n>0)?(n>=1e6?(n/1e6).toFixed(1).replace(/\\.0$/,"")+"M":Math.round(n/1e3)+"k"):"—";async function loadSessions(){try{const data=await json("/__bili/stats");const rows=(data.sessions||[]).map((item)=>"<tr><td>"+escapeHtml(item.title||"—")+"</td><td>"+escapeHtml(item.protocol||"—")+"</td><td class=mono>"+escapeHtml(item.label||"—")+"</td><td>"+escapeHtml(item.requests)+"</td><td>"+escapeHtml(item.contextTokens)+"</td><td class=mono title='"+escapeHtml(t("th.window_tip"))+"'>"+fmtW(item.contextWindow)+"</td><td>"+escapeHtml(new Date(item.lastSeen).toLocaleString())+(item.restored?" <span class=muted>"+t("sessions.restored")+"</span>":"")+"</td></tr>").join("");byId("sessions-body").innerHTML=rows||'<tr><td colspan="7">'+t("sessions.empty")+'</td></tr>'}catch(error){toast(String(error),true);throw error}}
async function refreshSessions(){const button=byId("refresh-sessions");busy(button,true,t("busy.refreshing"));try{await loadSessions();toast(t("toast.sessions_refreshed"))}catch{}finally{busy(button,false)}}
document.querySelectorAll(".copy-btn").forEach((btn)=>btn.addEventListener("click",async()=>{busy(btn,true,t("busy.copying"));try{await navigator.clipboard.writeText(btn.dataset.copy||"");toast(t("toast.copied"))}catch(e){toast(String(e),true)}finally{busy(btn,false)}}));async function clearPassthrough(){const button=byId("clear-passthrough");busy(button,true,t("busy.working"));try{await json("/__bili/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({passthrough:null})});toast(t("toast.passthrough_restored"));await loadConfig()}catch(error){toast(String(error),true)}finally{busy(button,false)}}
byId("clear-passthrough").addEventListener("click",clearPassthrough);
byId("save-upstream").addEventListener("click",saveUpstream);byId("test-upstream").addEventListener("click",testUpstream);byId("save-providers").addEventListener("click",saveProviders);byId("save-compress").addEventListener("click",saveCompress);byId("save-overrides").addEventListener("click",saveOverrides);byId("refresh-sessions").addEventListener("click",refreshSessions);
async function loadStatus(){try{const data=await json("/__bili/status");const banner=byId("stale-banner");if(banner){if(data.stale){banner.hidden=false;byId("stale-running").textContent=data.version||"";byId("stale-disk").textContent=data.diskVersion||"";byId("stale-mode").textContent=data.autoRestartOnUpdate?t("stale.on_auto"):t("stale.off_auto")}else{banner.hidden=true}}const cb=byId("conflicts-banner");if(cb){const c=data.conflicts;if(c&&c.events>0){cb.hidden=false;const kinds=Object.entries(c.kinds||{}).map(([k,v])=>k+"×"+v).join(", ");byId("conflicts-summary").textContent="("+c.events+" event(s) in "+c.sessions+" session(s): "+kinds+")"}else{cb.hidden=true}}}catch{}}
Promise.all([loadConfig(),loadUpstream(),loadStatus()]).catch((error)=>toast(String(error),true));setInterval(()=>{if(byId("page-sessions").classList.contains("active"))loadSessions().catch(()=>{})},5000);
`;
