import { existsSync } from "node:fs";
import { rootCaPath } from "../ca.js";
import { WEB_CLIENT } from "./client.js";
import { WEB_STYLES } from "./styles.js";
import { translate } from "./i18n.js";

const zh = (key: string) => translate("zh-CN", key);

function escapeHtml(value: string): string {
    return value.replace(/[&<>"']/g, (char) =>
        char === "&" ? "&amp;" : char === "<" ? "&lt;" : char === ">" ? "&gt;" : char === '"' ? "&quot;" : "&#39;");
}

export function renderPage(origin: string, version: string): string {
    const caPath = rootCaPath();
    const caPathEsc = escapeHtml(caPath);
    const caReady = existsSync(caPath);
    return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>sigma</title><style>${WEB_STYLES}</style></head><body>
<div class="app"><aside class="sidebar"><div class="brand"><div class="brand-title">billion<span>-context</span></div><div class="version">v${version}</div></div><a class="fork-ribbon" href="https://github.com/ranxianglei/sigma" target="_blank" rel="noopener">★ Fork me on GitHub</a><nav class="nav"><button class="active" data-page="overview" data-i18n="nav.overview">${zh("nav.overview")}</button><button data-page="routing" data-i18n="nav.routing">${zh("nav.routing")}</button><button data-page="upstream" data-i18n="nav.upstream">${zh("nav.upstream")}</button><button data-page="sessions" data-i18n="nav.sessions">${zh("nav.sessions")}</button><button data-page="settings" data-i18n="nav.settings">${zh("nav.settings")}</button></nav><button id="language-toggle" class="language-toggle">English</button></aside>
<main class="main"><section id="page-overview" class="page active"><h1 data-i18n="nav.overview">${zh("nav.overview")}</h1><p class="lead" data-i18n="overview.lead">${zh("overview.lead")}</p><div id="passthrough-banner" class="notice" hidden>⚠️ <strong data-i18n="pt.on">${zh("pt.on")}</strong><span data-i18n="pt.desc">${zh("pt.desc")}</span><span id="passthrough-source" class="mono"></span><span data-i18n="pt.tail">${zh("pt.tail")}</span> <button id="clear-passthrough" class="btn" data-i18n="pt.restore">${zh("pt.restore")}</button></div><div id="stale-banner" class="notice" hidden>⚠️ <strong data-i18n="stale.on">${zh("stale.on")}</strong><span data-i18n="stale.run">${zh("stale.run")}</span><span id="stale-running" class="mono"></span><span data-i18n="stale.disk">${zh("stale.disk")}</span><span id="stale-disk" class="mono"></span><span data-i18n="stale.restart">${zh("stale.restart")}</span><span id="stale-mode"></span><span data-i18n="stale.close">${zh("stale.close")}</span></div><div id="conflicts-banner" class="notice" hidden>⚠️ <strong data-i18n="conflict.on">${zh("conflict.on")}</strong><span data-i18n="conflict.desc">${zh("conflict.desc")}</span><span id="conflicts-summary" class="mono"></span></div><div class="grid"><div class="card"><h2 data-i18n="overview.service">${zh("overview.service")}</h2><p class="mono">${origin}</p></div><div class="card"><h2 data-i18n="client.title">${zh("client.title")}</h2><p class="status" data-i18n="overview.client_hint">${zh("overview.client_hint")}</p></div></div></section>
<section id="page-routing" class="page"><h1 data-i18n="client.title">${zh("client.title")}</h1><p class="lead"><span data-i18n="routing.lead_a">${zh("routing.lead_a")}</span><span class="mono">/sigma/</span><span data-i18n="routing.lead_b">${zh("routing.lead_b")}</span></p>
<h2 class="section-title" data-i18n="routing.a_title">${zh("routing.a_title")}</h2>
<p class="hint"><span data-i18n="routing.a_hint_a">${zh("routing.a_hint_a")}</span><span class="mono">${origin}/sigma/</span><span data-i18n="routing.a_hint_b">${zh("routing.a_hint_b")}</span></p>
<div class="card"><div class="card-head"><h2>OpenCode</h2><button class="btn small copy-btn" data-copy="${origin}/sigma/https://open.bigmodel.cn/api/coding/paas/v4" data-i18n="copy">${zh("copy")}</button></div><dl class="kv"><dt data-i18n="dt.config_file">${zh("dt.config_file")}</dt><dd class="mono">~/.config/opencode/opencode.json</dd><dt>baseURL</dt><dd class="mono">${origin}/sigma/https://open.bigmodel.cn/api/coding/paas/v4</dd></dl></div>
<div class="card"><div class="card-head"><h2 data-i18n="card.codex_key">${zh("card.codex_key")}</h2><button class="btn small copy-btn" data-copy="${origin}/sigma/https://api.openai.com/v1" data-i18n="copy">${zh("copy")}</button></div><dl class="kv"><dt data-i18n="dt.config_file">${zh("dt.config_file")}</dt><dd class="mono">~/.codex/config.toml</dd><dt>base_url</dt><dd class="mono">${origin}/sigma/https://api.openai.com/v1</dd></dl></div>
<div class="card"><div class="card-head"><h2 data-i18n="card.codex_login">${zh("card.codex_login")}</h2><button class="btn small copy-btn" data-copy="openai_base_url = &quot;${origin}/sigma/https://chatgpt.com/backend-api/codex&quot;" data-i18n="copy.config">${zh("copy.config")}</button></div><dl class="kv"><dt data-i18n="dt.config_file">${zh("dt.config_file")}</dt><dd class="mono">~/.codex/config.toml</dd><dt data-i18n="dt.config">${zh("dt.config")}</dt><dd class="mono">openai_base_url = "${origin}/sigma/https://chatgpt.com/backend-api/codex"</dd><dt data-i18n="dt.auth">${zh("dt.auth")}</dt><dd><span class="mono">codex login</span><span data-i18n="routing.codex_auth_note">${zh("routing.codex_auth_note")}</span></dd><dt data-i18n="dt.notes">${zh("dt.notes")}</dt><dd><span data-i18n="routing.codex_note_a">${zh("routing.codex_note_a")}</span><span class="mono">model_provider</span><span data-i18n="routing.codex_note_b">${zh("routing.codex_note_b")}</span><span class="mono">model_provider = "openai"</span><span data-i18n="routing.codex_note_c">${zh("routing.codex_note_c")}</span><span class="mono">NO_PROXY=localhost,127.0.0.1</span><span data-i18n="routing.codex_note_d">${zh("routing.codex_note_d")}</span><span class="mono">localhost</span><span data-i18n="routing.codex_note_e">${zh("routing.codex_note_e")}</span></dd></dl></div>
<div class="card"><div class="card-head"><h2 data-i18n="card.claude_key">${zh("card.claude_key")}</h2><button class="btn small copy-btn" data-copy="${origin}/sigma/https://api.anthropic.com" data-i18n="copy">${zh("copy")}</button></div><dl class="kv"><dt data-i18n="dt.env">${zh("dt.env")}</dt><dd class="mono">ANTHROPIC_BASE_URL=${origin}/sigma/https://api.anthropic.com</dd></dl></div>
<div class="card"><div class="card-head"><h2>Pi</h2><span class="badge" data-i18n="badge.not_recommended">${zh("badge.not_recommended")}</span><button class="btn small copy-btn" data-copy="${origin}/sigma/https://api.anthropic.com" data-i18n="copy">${zh("copy")}</button></div><dl class="kv"><dt data-i18n="dt.config_file">${zh("dt.config_file")}</dt><dd class="mono">~/.pi/agent/models.json</dd><dt>baseUrl</dt><dd class="mono">${origin}/sigma/https://api.anthropic.com</dd></dl><p class="hint" data-i18n="pi.hint">${zh("pi.hint")}</p></div>
<div class="card"><div class="card-head"><h2 data-i18n="other.title">${zh("other.title")}</h2><button class="btn small copy-btn" data-copy="${origin}/sigma/" data-i18n="copy">${zh("copy")}</button></div><dl class="kv"><dt data-i18n="dt.rule">${zh("dt.rule")}</dt><dd><span data-i18n="other.rule">${zh("other.rule")}</span><span class="mono">${origin}/sigma/</span></dd><dt data-i18n="dt.example">${zh("dt.example")}</dt><dd class="mono">${origin}/sigma/https://api.openai.com/v1</dd></dl></div>
<h2 class="section-title" data-i18n="routing.b_title">${zh("routing.b_title")}</h2>
<p class="hint" data-i18n="routing.b_hint">${zh("routing.b_hint")}</p>
<div class="card"><div class="card-head"><h2 data-i18n="zcode.title">${zh("zcode.title")}</h2><span class="badge">MITM</span><button class="btn small copy-btn" data-copy="${caPathEsc}" data-i18n="copy.ca">${zh("copy.ca")}</button></div><dl class="kv"><dt data-i18n="dt.method">${zh("dt.method")}</dt><dd data-i18n="zcode.method">${zh("zcode.method")}</dd><dt data-i18n="dt.setting">${zh("dt.setting")}</dt><dd>Settings → Network → HTTP Proxy = <span class="mono">${origin}</span></dd><dt data-i18n="dt.ca_cert">${zh("dt.ca_cert")}</dt><dd class="mono">${caPathEsc}${caReady ? "" : `<span data-i18n="ca.not_ready">${zh("ca.not_ready")}</span>`}</dd></dl><p class="hint"><span data-i18n="zcode.hint_a">${zh("zcode.hint_a")}</span><span class="mono">~</span><span data-i18n="zcode.hint_b">${zh("zcode.hint_b")}</span><span class="mono">~/…</span><span data-i18n="zcode.hint_c">${zh("zcode.hint_c")}</span></p></div></section>
<section id="page-upstream" class="page"><h1 data-i18n="upstream.title">${zh("upstream.title")}</h1><p class="lead" data-i18n="upstream.lead">${zh("upstream.lead")}</p><div class="card"><div class="card-head"><h2 data-i18n="upstream.global">${zh("upstream.global")}</h2></div><div class="modes"><label><input type="radio" name="proxy-mode" value="direct" checked><span data-i18n="upstream.mode.direct">${zh("upstream.mode.direct")}</span></label><label><input type="radio" name="proxy-mode" value="manual"><span data-i18n="upstream.mode.manual">${zh("upstream.mode.manual")}</span></label><label><input type="radio" name="proxy-mode" value="auto"><span data-i18n="upstream.mode.auto">${zh("upstream.mode.auto")}</span></label></div><div class="field"><label>HTTP / HTTPS Proxy</label><input id="proxy-url" class="mono" placeholder="http://127.0.0.1:7897"></div><dl class="kv"><dt data-i18n="upstream.source">${zh("upstream.source")}</dt><dd id="upstream-source" data-i18n="upstream.direct">${zh("upstream.direct")}</dd><dt data-i18n="upstream.effective">${zh("upstream.effective")}</dt><dd id="upstream-effective" class="mono">direct</dd><dt data-i18n="upstream.pac">${zh("upstream.pac")}</dt><dd id="upstream-pac" class="mono">—</dd><dt data-i18n="upstream.state">${zh("upstream.state")}</dt><dd id="upstream-state" class="status" data-i18n="upstream.untested">${zh("upstream.untested")}</dd></dl><div class="actions"><button id="save-upstream" class="btn primary" data-i18n="upstream.save">${zh("upstream.save")}</button><button id="test-upstream" class="btn" data-i18n="upstream.test">${zh("upstream.test")}</button></div></div><div class="card"><div class="card-head"><h2 data-i18n="upstream.overrides_title">${zh("upstream.overrides_title")}</h2></div><p class="status" data-i18n="upstream.overrides_desc">${zh("upstream.overrides_desc")}</p><div id="upstream-overrides" class="status" data-i18n="upstream.loading">${zh("upstream.loading")}</div><div class="actions"><button id="save-overrides" class="btn primary" data-i18n="upstream.save_overrides">${zh("upstream.save_overrides")}</button></div></div></section>
<section id="page-sessions" class="page"><div class="card-head"><div><h1 data-i18n="nav.sessions">${zh("nav.sessions")}</h1><p class="lead" data-i18n="sessions.lead">${zh("sessions.lead")}</p></div><button id="refresh-sessions" class="btn" data-i18n="sessions.refresh">${zh("sessions.refresh")}</button></div><div class="card"><table><thead><tr><th data-i18n="th.title">${zh("th.title")}</th><th data-i18n="th.protocol">${zh("th.protocol")}</th><th data-i18n="th.label">${zh("th.label")}</th><th data-i18n="th.requests">${zh("th.requests")}</th><th data-i18n="th.context">${zh("th.context")}</th><th data-i18n="th.window" data-i18n-title="th.window_tip" title="${zh("th.window_tip")}">${zh("th.window")}</th><th data-i18n="th.last_seen">${zh("th.last_seen")}</th></tr></thead><tbody id="sessions-body"></tbody></table></div></section>
<section id="page-settings" class="page"><h1 data-i18n="settings.title">${zh("settings.title")}</h1><p class="lead" data-i18n="settings.lead">${zh("settings.lead")}</p><div class="card"><div class="field"><label>providers JSON</label><textarea id="providers-json">{}</textarea></div><div class="actions"><button id="save-providers" class="btn primary" data-i18n="settings.save_apply">${zh("settings.save_apply")}</button></div></div><div class="card"><div class="card-head"><h2 data-i18n="settings.compress_title">${zh("settings.compress_title")}</h2></div><p class="status" data-i18n="settings.compress_desc">${zh("settings.compress_desc")}</p><div class="field"><label>compress JSON</label><textarea id="compress-json" placeholder='{"modelContextLimit": 200000}'></textarea></div><div class="actions"><button id="save-compress" class="btn primary" data-i18n="upstream.save">${zh("upstream.save")}</button></div></div></section></main></div><div id="toast" class="toast"></div><script>${WEB_CLIENT}</script></body></html>`;
}
