// zcode native mode (#1145): pure JSON surgery for the two ZCode provider
// store generations. Legacy clients read `v2/config.json`
// (`{provider:{<id>:{options:{baseURL}}}}`); current clients overlay
// `v2/provider_config.json` (`{schemaVersion:1,config:{providerConfigRules:{
// providerRules:[...]}}}`, strict schema, personal wins over builtin). Both
// are machine-generated by ZCode, so atomic re-serialization is safe and all
// unknown fields are preserved verbatim. Malformed input throws loudly —
// never merge into defaults, never partial-write (§7.3).

import fs from "node:fs";
import path from "node:path";
import { zcodeDataRoot } from "../client-config.js";

export type ZcodeStoreKind = "legacy" | "new";

export interface ZcodeWrappedEntry {
    readonly id: string;
    readonly upstream: string;
}

export const ZCODE_PLUGIN_HEADER = "x-sigma-plugin";
export const ZCODE_AGENT_VALUE = "zcode";
export const ZCODE_BIGMODEL_ANTHROPIC_UPSTREAM = "https://open.bigmodel.cn/api/anthropic";

const ZCODE_LEGACY_PLAN_IDS: readonly string[] = [
    "builtin:bigmodel-coding-plan",
    "builtin:zai-coding-plan",
    "builtin:bigmodel-start-plan",
    "builtin:zai-start-plan",
    "builtin:bigmodel",
    "builtin:zai",
];

const ZCODE_NEW_PLAN_IDS: readonly string[] = [
    "account:bigmodel-individual-coding-plan",
    "account:bigmodel-team-coding-plan",
    "account:bigmodel-start-plan",
    "account:zai-individual-coding-plan",
    "account:zai-team-coding-plan",
    "account:zai-start-plan",
];

const ZCODE_LEGACY_CREATE_IDS: readonly string[] = [
    "builtin:bigmodel-coding-plan",
    "builtin:bigmodel-start-plan",
];

const ZCODE_NEW_CREATE_IDS: readonly string[] = [
    "account:bigmodel-individual-coding-plan",
    "account:bigmodel-team-coding-plan",
    "account:bigmodel-start-plan",
];

const WRAPPED_URL_RE = /^https?:\/\/[^/]+\/sigma\/(https?:\/\/.+)$/;

export function resolveZcodeDataDir(env: NodeJS.ProcessEnv = process.env): string {
    return zcodeDataRoot(env);
}

/** Candidate store files in precedence order. An explicit
 *  ZCODE_PERSONAL_PROVIDER_CONFIG_FILE (absolute file override, upstream
 *  provider-runtime-env.ts) outranks the derived path; dataDir stays the
 *  single source when callers inject it (tests). */
export function zcodeStoreCandidates(dataDir: string, kind: ZcodeStoreKind, env: NodeJS.ProcessEnv = process.env): string[] {
    const local = path.join(dataDir, "v2", kind === "new" ? "provider_config.json" : "config.json");
    if (kind !== "new") return [local];
    const explicit = env.ZCODE_PERSONAL_PROVIDER_CONFIG_FILE?.trim();
    return explicit !== undefined && explicit.length > 0 ? [explicit, local] : [local];
}

/** Pick the store the running client actually honors: the new personal store
 *  when it exists AND parses with the expected shape, else the legacy file
 *  (both readers stay live in current builds during the migration window). */
export function detectZcodeStore(dataDir: string, env: NodeJS.ProcessEnv = process.env): { kind: ZcodeStoreKind; file: string } {
    for (const newFile of zcodeStoreCandidates(dataDir, "new", env)) {
        try {
            assertNewStoreShape(JSON.parse(fs.readFileSync(newFile, "utf8")));
            return { kind: "new", file: newFile };
        } catch {}
    }
    return { kind: "legacy", file: zcodeStoreCandidates(dataDir, "legacy", env)[0] };
}

function asRecord(value: unknown): Record<string, unknown> | undefined {
    return value !== null && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>) : undefined;
}

function parseRoot(text: string, label: string): Record<string, unknown> {
    let doc: unknown;
    try {
        doc = JSON.parse(text);
    } catch (err) {
        throw new Error(`${label} is not valid JSON: ${err instanceof Error ? err.message : String(err)}`);
    }
    const root = asRecord(doc);
    if (!root) throw new Error(`${label} must be a JSON object`);
    return root;
}

/** Strip a previous /sigma/ wrapper (any origin/port) and validate the result
 *  is an http(s) URL. Returns undefined for values we must not touch. */
function unwrapBaseUrl(value: unknown): string | undefined {
    if (typeof value !== "string") return undefined;
    const match = WRAPPED_URL_RE.exec(value);
    const candidate = match ? match[1] : value;
    try {
        const url = new URL(candidate);
        return url.protocol === "http:" || url.protocol === "https:" ? candidate : undefined;
    } catch {
        return undefined;
    }
}

function serialize(root: Record<string, unknown>): string {
    return `${JSON.stringify(root, null, 2)}\n`;
}

interface LegacyEntry {
    readonly id: string;
    readonly options: Record<string, unknown>;
}

function legacyPlanEntries(root: Record<string, unknown>, createWhenEmpty: boolean): LegacyEntry[] {
    let provider = asRecord(root.provider);
    if (!provider) {
        if (!createWhenEmpty) return [];
        provider = {};
        root.provider = provider;
    }
    const found: LegacyEntry[] = [];
    for (const id of ZCODE_LEGACY_PLAN_IDS) {
        const entry = asRecord(provider[id]);
        if (!entry) continue;
        let options = asRecord(entry.options);
        if (!options) {
            options = {};
            entry.options = options;
        }
        found.push({ id, options });
    }
    if (found.length > 0) return found;
    if (!createWhenEmpty) return [];
    for (const id of ZCODE_LEGACY_CREATE_IDS) {
        const entry: Record<string, unknown> = { options: {} };
        provider[id] = entry;
        found.push({ id, options: entry.options as Record<string, unknown> });
    }
    return found;
}

function applyLegacy(text: string, origin: string): { text: string; wrapped: ZcodeWrappedEntry[] } {
    const root = parseRoot(text, "zcode v2/config.json");
    const wrapped: ZcodeWrappedEntry[] = [];
    for (const { id, options } of legacyPlanEntries(root, true)) {
        const upstream = unwrapBaseUrl(options.baseURL) ?? ZCODE_BIGMODEL_ANTHROPIC_UPSTREAM;
        options.baseURL = `${origin}/sigma/${upstream}`;
        wrapped.push({ id, upstream });
    }
    return { text: serialize(root), wrapped };
}

function assertNewStoreShape(doc: unknown): void {
    const root = asRecord(doc);
    if (!root) throw new Error("zcode provider_config.json must be a JSON object");
    if (root.schemaVersion !== 1) throw new Error(`unsupported provider_config.json schemaVersion: ${String(root.schemaVersion)}`);
    const config = asRecord(root.config);
    if (!config) throw new Error("provider_config.json is missing its config object");
    const rulesField = asRecord(config.providerConfigRules);
    if (rulesField !== undefined && !Array.isArray(rulesField.providerRules)) {
        throw new Error("provider_config.json config.providerConfigRules.providerRules must be an array");
    }
}

interface NewRule {
    readonly id: string;
    readonly api: Record<string, unknown>;
}

function newPlanRules(root: Record<string, unknown>, createWhenEmpty: boolean): NewRule[] {
    const config = asRecord(root.config);
    if (!config) throw new Error("provider_config.json is missing its config object");
    let rulesField = asRecord(config.providerConfigRules);
    if (!rulesField) {
        if (!createWhenEmpty) return [];
        rulesField = { providerRules: [] };
        config.providerConfigRules = rulesField;
    }
    const rules = Array.isArray(rulesField.providerRules) ? (rulesField.providerRules as unknown[]) : [];
    const found: NewRule[] = [];
    for (const raw of rules) {
        const rule = asRecord(raw);
        if (!rule || typeof rule.providerId !== "string" || !ZCODE_NEW_PLAN_IDS.includes(rule.providerId)) continue;
        const configObj = asRecord(rule.config);
        if (!configObj) continue;
        let api = asRecord(configObj.api);
        if (!api) {
            api = {};
            configObj.api = api;
        }
        found.push({ id: rule.providerId, api });
    }
    if (found.length > 0) return found;
    if (!createWhenEmpty) return [];
    for (const id of ZCODE_NEW_CREATE_IDS) {
        const rule: Record<string, unknown> = { providerId: id, config: { api: {} } };
        rules.push(rule);
        const api = (asRecord(asRecord(rule.config)?.api) ?? {}) as Record<string, unknown>;
        found.push({ id, api });
    }
    return found;
}

function applyNew(text: string, origin: string): { text: string; wrapped: ZcodeWrappedEntry[] } {
    const root = parseRoot(text, "zcode v2/provider_config.json");
    assertNewStoreShape(root);
    const wrapped: ZcodeWrappedEntry[] = [];
    for (const { id, api } of newPlanRules(root, true)) {
        const upstream = unwrapBaseUrl(api.baseUrl) ?? ZCODE_BIGMODEL_ANTHROPIC_UPSTREAM;
        api.baseUrl = `${origin}/sigma/${upstream}`;
        wrapped.push({ id, upstream });
    }
    return { text: serialize(root), wrapped };
}

export function applyZcodeRouting(text: string, kind: ZcodeStoreKind, origin: string): { text: string; wrapped: ZcodeWrappedEntry[] } {
    return kind === "new" ? applyNew(text, origin) : applyLegacy(text, origin);
}

function stampHeaders(headers: unknown): Record<string, unknown> | undefined {
    const existing = asRecord(headers);
    const next: Record<string, unknown> = existing ? { ...existing } : {};
    next[ZCODE_PLUGIN_HEADER] = ZCODE_AGENT_VALUE;
    return next;
}

function stampLegacy(text: string): string {
    const root = parseRoot(text, "zcode v2/config.json");
    let changed = false;
    const provider = asRecord(root.provider);
    if (provider) {
        for (const id of ZCODE_LEGACY_PLAN_IDS) {
            const options = asRecord(asRecord(provider[id])?.options);
            if (!options || !WRAPPED_URL_RE.test(String(options.baseURL))) continue;
            const stamped = stampHeaders(options.headers);
            if (stamped) {
                options.headers = stamped;
                changed = true;
            }
        }
    }
    return changed ? serialize(root) : text;
}

function stampNew(text: string): string {
    const root = parseRoot(text, "zcode v2/provider_config.json");
    assertNewStoreShape(root);
    let changed = false;
    const rulesField = asRecord(asRecord(root.config)?.providerConfigRules);
    const rules = rulesField && Array.isArray(rulesField.providerRules) ? (rulesField.providerRules as unknown[]) : [];
    for (const raw of rules) {
        const api = asRecord(asRecord(asRecord(raw)?.config)?.api);
        if (!api || !WRAPPED_URL_RE.test(String(api.baseUrl))) continue;
        const stamped = stampHeaders(api.headers);
        if (stamped) {
            api.headers = stamped;
            changed = true;
        }
    }
    return changed ? serialize(root) : text;
}

export function stampZcodePluginHeader(text: string, kind: ZcodeStoreKind): string {
    return kind === "new" ? stampNew(text) : stampLegacy(text);
}

function unrouteHeaders(headers: unknown): void {
    const existing = asRecord(headers);
    if (existing && Object.prototype.hasOwnProperty.call(existing, ZCODE_PLUGIN_HEADER)) delete existing[ZCODE_PLUGIN_HEADER];
}

function unrouteLegacy(text: string): { text: string; changed: boolean } {
    const root = parseRoot(text, "zcode v2/config.json");
    let changed = false;
    const provider = asRecord(root.provider);
    if (provider) {
        for (const id of ZCODE_LEGACY_PLAN_IDS) {
            const options = asRecord(asRecord(provider[id])?.options);
            if (!options || typeof options.baseURL !== "string") continue;
            const match = WRAPPED_URL_RE.exec(options.baseURL);
            if (!match) continue;
            options.baseURL = match[1];
            unrouteHeaders(options.headers);
            changed = true;
        }
    }
    return { text: changed ? serialize(root) : text, changed };
}

function unrouteNew(text: string): { text: string; changed: boolean } {
    const root = parseRoot(text, "zcode v2/provider_config.json");
    assertNewStoreShape(root);
    let changed = false;
    const rulesField = asRecord(asRecord(root.config)?.providerConfigRules);
    const rules = rulesField && Array.isArray(rulesField.providerRules) ? (rulesField.providerRules as unknown[]) : [];
    for (const raw of rules) {
        const api = asRecord(asRecord(asRecord(raw)?.config)?.api);
        if (!api || typeof api.baseUrl !== "string") continue;
        const match = WRAPPED_URL_RE.exec(api.baseUrl);
        if (!match) continue;
        api.baseUrl = match[1];
        unrouteHeaders(api.headers);
        changed = true;
    }
    return { text: changed ? serialize(root) : text, changed };
}

export function unrouteZcodeText(text: string, kind: ZcodeStoreKind): { text: string; changed: boolean } {
    return kind === "new" ? unrouteNew(text) : unrouteLegacy(text);
}

/** Read-only inspection for status reporting: which store exists and which
 *  entries currently route through a sigma origin. */
export function inspectZcodeRouting(dataDir: string, env: NodeJS.ProcessEnv = process.env): { kind: ZcodeStoreKind; file: string; wrapped: ZcodeWrappedEntry[] } | undefined {
    const { kind, file } = detectZcodeStore(dataDir, env);
    let text: string;
    try {
        text = fs.readFileSync(file, "utf8");
    } catch {
        return undefined;
    }
    let doc: unknown;
    try {
        doc = JSON.parse(text);
    } catch {
        return undefined;
    }
    if (kind === "new") {
        const root = asRecord(doc);
        if (!root) return undefined;
        try {
            assertNewStoreShape(root);
        } catch {
            return undefined;
        }
        const rulesField = asRecord(asRecord(root.config)?.providerConfigRules);
        const rules = rulesField && Array.isArray(rulesField.providerRules) ? (rulesField.providerRules as unknown[]) : [];
        const wrapped: ZcodeWrappedEntry[] = [];
        for (const raw of rules) {
            const rule = asRecord(raw);
            if (!rule || typeof rule.providerId !== "string" || !ZCODE_NEW_PLAN_IDS.includes(rule.providerId)) continue;
            const baseUrl = asRecord(asRecord(rule.config)?.api)?.baseUrl;
            const match = typeof baseUrl === "string" ? WRAPPED_URL_RE.exec(baseUrl) : undefined;
            if (match) wrapped.push({ id: rule.providerId, upstream: match[1] });
        }
        return { kind, file, wrapped };
    }
    const root = asRecord(doc);
    const provider = root ? asRecord(root.provider) : undefined;
    if (!provider) return undefined;
    const wrapped: ZcodeWrappedEntry[] = [];
    for (const id of ZCODE_LEGACY_PLAN_IDS) {
        const baseUrl = asRecord(asRecord(provider[id])?.options)?.baseURL;
        const match = typeof baseUrl === "string" ? WRAPPED_URL_RE.exec(baseUrl) : undefined;
        if (match) wrapped.push({ id, upstream: match[1] });
    }
    return { kind, file, wrapped };
}
