// zcode native mode (#1145): pure JSON surgery for the two ZCode provider
// store generations. Legacy clients read `v2/config.json`
// (`{provider:{<id>:{options:{baseURL}}}}`); current clients overlay
// `v2/provider_config.json` (`{schemaVersion:1,config:{providerConfigRules:{
// providerRules:[...]}}}`, strict schema, personal wins over builtin). Both
// are machine-generated by ZCode, so atomic re-serialization is safe and all
// unknown fields are preserved verbatim. Malformed input throws loudly —
// never merge into defaults, never partial-write (§7.3).

import fs from "node:fs";
import path from "node:path";
import { zcodeDataRoot } from "../client-config.js";

export type ZcodeStoreKind = "legacy" | "new";

export interface ZcodeWrappedEntry {
    readonly id: string;
    readonly upstream: string;
}

export const ZCODE_PLUGIN_HEADER = "x-sigma-plugin";
export const ZCODE_AGENT_VALUE = "zcode";
export const ZCODE_BIGMODEL_ANTHROPIC_UPSTREAM = "https://open.bigmodel.cn/api/anthropic";

const ZCODE_LEGACY_PLAN_IDS: readonly string[] = [
    "builtin:bigmodel-coding-plan",
    "builtin:zai-coding-plan",
    "builtin:bigmodel-start-plan",
    "builtin:zai-start-plan",
    "builtin:bigmodel",
    "builtin:zai",
];

const ZCODE_NEW_PLAN_IDS: readonly string[] = [
    "account:bigmodel-individual-coding-plan",
    "account:bigmodel-team-coding-plan",
    "account:bigmodel-start-plan",
    "account:zai-individual-coding-plan",
    "account:zai-team-coding-plan",
    "account:zai-start-plan",
];

const ZCODE_LEGACY_CREATE_IDS: readonly string[] = [
    "builtin:bigmodel-coding-plan",
    "builtin:bigmodel-start-plan",
];

const ZCODE_NEW_CREATE_IDS: readonly string[] = [
    "account:bigmodel-individual-coding-plan",
    "account:bigmodel-team-coding-plan",
    "account:bigmodel-start-plan",
];

const WRAPPED_URL_RE = /^https?:\/\/[^/]+\/sigma\/(https?:\/\/.+)$/;

export function resolveZcodeDataDir(env: NodeJS.ProcessEnv = process.env): string {
    return zcodeDataRoot(env);
}

/** Candidate store files in precedence order. An explicit
 *  ZCODE_PERSONAL_PROVIDER_CONFIG_FILE (absolute file override, upstream
 *  provider-runtime-env.ts) outranks the derived path; dataDir stays the
 *  single source when callers inject it (tests). */
export function zcodeStoreCandidates(dataDir: string, kind: ZcodeStoreKind, env: NodeJS.ProcessEnv = process.env): string[] {
    const local = path.join(dataDir, "v2", kind === "new" ? "provider_config.json" : "config.json");
    if (kind !== "new") return [local];
    const explicit = env.ZCODE_PERSONAL_PROVIDER_CONFIG_FILE?.trim();
    return explicit !== undefined && explicit.length > 0 ? [explicit, local] : [local];
}

/** Pick the store the running client actually honors: the new personal store
 *  when it exists AND parses with the expected shape, else the legacy file
 *  (both readers stay live in current builds during the migration window). */
export function detectZcodeStore(dataDir: string, env: NodeJS.ProcessEnv = process.env): { kind: ZcodeStoreKind; file: string } {
    for (const newFile of zcodeStoreCandidates(dataDir, "new", env)) {
        try {
            assertNewStoreShape(JSON.parse(fs.readFileSync(newFile, "utf8")));
            return { kind: "new", file: newFile };
        } catch {}
    }
    return { kind: "legacy", file: zcodeStoreCandidates(dataDir, "legacy", env)[0] };
}

/** Routing scope + exemptions for the zcode provider store (#1622).
 *  Default "all" mirrors the in-process natives (pi/dsh): every provider
 *  rides compression, a loopback target is never re-proxied (#809), and
 *  explicit exemptions are opt-in. */
export interface ZcodeRoutePolicy {
    readonly route: "all" | "plans" | "none";
    /** Normalized provider-route URL keys declaring `direct: true` (#1622):
    *  entries whose upstream matches one of these prefixes stay direct. */
    readonly directPrefixes: readonly string[];
    /** #1621 escape hatch for ZCode builds that fixed ClientRequestSigningV4. */
    readonly assumeSigningFixed: boolean;
}

export function defaultZcodeRoutePolicy(): ZcodeRoutePolicy {
    return { route: "all", directPrefixes: [], assumeSigningFixed: false };
}

/** #1621: the v3.14+ personal-store generation ships ClientRequestSigningV4
 *  for coding-plan accounts. Its handshake builder rejects non-https origins
 *  (allowInsecureHttp is never passed anywhere in zcode) and derives the
 *  handshake path from origin alone, dropping any /bili/ prefix — so a
 *  /bili/-wrapped baseUrl fails at model creation ("Client signing handshake
 *  requires HTTPS."). Under route:"all" those accounts are skipped per-entry
 *  (every other provider still routes); under route:"plans" the plan targets
 *  ARE the signing accounts, so nothing is routable and the whole store is
 *  left untouched. assumeSigningFixed flips both off once zcode ships the fix. */
export function zcodeSigningBlocksRouting(kind: ZcodeStoreKind, policy: ZcodeRoutePolicy = defaultZcodeRoutePolicy()): boolean {
    return kind === "new" && !policy.assumeSigningFixed && policy.route === "plans";
}

/** #809 parity with the in-process natives: a loopback proxy target is never
 *  re-proxied — wrapping it would stack bili onto itself or onto the user's
 *  own local relay. */
function isLoopbackHttpUrl(url: string): boolean {
    let parsed: URL;
    try {
        parsed = new URL(url);
    } catch {
        return false;
    }
    if (parsed.protocol !== "http:" && parsed.protocol !== "https:") return false;
    const host = parsed.hostname.toLowerCase();
    return host === "localhost" || host === "::1" || host === "[::1]" || host === "0.0.0.0"
        || host === "127.0.0.1" || /^127\.\d+\.\d+\.\d+$/.test(host);
}

/** An exemption hits when a `direct: true` provider-route key matches the
 *  upstream — same boundary rule as findRoute (upstream === key OR upstream
 *  starts with key + "/"), so "https://x.com" never matches
 *  "https://x.com.evil". Provider-ID granularity is not offered: two store
 *  entries sharing one upstream URL are exempted together (the URL is the
 *  user-facing identity in the providers table). */
function directExemptionHit(upstream: string | undefined, directPrefixes: readonly string[]): boolean {
    if (upstream === undefined) return false;
    for (const key of directPrefixes) {
        if (key.length === 0) continue;
        if (upstream === key || upstream.startsWith(key + "/")) return true;
    }
    return false;
}

/** Why this entry must NOT be wrapped under the policy — undefined = route it.
 *  `upstream` is the unwrapped target (undefined when there is no usable
 *  http(s) baseUrl). */
function zcodeEntrySkipReason(id: string, upstream: string | undefined, hasBaseUrl: boolean, kind: ZcodeStoreKind, policy: ZcodeRoutePolicy): string | undefined {
    if (kind === "new" && !policy.assumeSigningFixed && policy.route === "all" && ZCODE_NEW_PLAN_IDS.includes(id)) {
        return "client-signing account (#1621) — stays direct; use cert-MITM for compression on this account";
    }
    if (!hasBaseUrl) return "no usable http(s) baseUrl — left untouched";
    if (upstream !== undefined && isLoopbackHttpUrl(upstream)) return `loopback target (${upstream}) never re-proxied (#809)`;
    if (directExemptionHit(upstream, policy.directPrefixes)) return "direct exemption (providers route `direct: true`)";
    return undefined;
}

function asRecord(value: unknown): Record<string, unknown> | undefined {
    return value !== null && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>) : undefined;
}

function parseRoot(text: string, label: string): Record<string, unknown> {
    let doc: unknown;
    try {
        doc = JSON.parse(text);
    } catch (err) {
        throw new Error(`${label} is not valid JSON: ${err instanceof Error ? err.message : String(err)}`);
    }
    const root = asRecord(doc);
    if (!root) throw new Error(`${label} must be a JSON object`);
    return root;
}

/** Strip a previous /sigma/ wrapper (any origin/port) and validate the result
 *  is an http(s) URL. Returns undefined for values we must not touch. */
function unwrapBaseUrl(value: unknown): string | undefined {
    if (typeof value !== "string") return undefined;
    const match = WRAPPED_URL_RE.exec(value);
    const candidate = match ? match[1] : value;
    try {
        const url = new URL(candidate);
        return url.protocol === "http:" || url.protocol === "https:" ? candidate : undefined;
    } catch {
        return undefined;
    }
}

function serialize(root: Record<string, unknown>): string {
    return `${JSON.stringify(root, null, 2)}\n`;
}

interface LegacyEntry {
    readonly id: string;
    readonly options: Record<string, unknown>;
}

function legacyPlanEntries(root: Record<string, unknown>, createWhenEmpty: boolean): LegacyEntry[] {
    let provider = asRecord(root.provider);
    if (!provider) {
        if (!createWhenEmpty) return [];
        provider = {};
        root.provider = provider;
    }
    const found: LegacyEntry[] = [];
    for (const id of ZCODE_LEGACY_PLAN_IDS) {
        const entry = asRecord(provider[id]);
        if (!entry) continue;
        let options = asRecord(entry.options);
        if (!options) {
            options = {};
            entry.options = options;
        }
        found.push({ id, options });
    }
    if (found.length > 0) return found;
    if (!createWhenEmpty) return [];
    for (const id of ZCODE_LEGACY_CREATE_IDS) {
        const entry: Record<string, unknown> = { options: {} };
        provider[id] = entry;
        found.push({ id, options: entry.options as Record<string, unknown> });
    }
    return found;
}

/** #1622 route:"all" selection for the legacy store — mirrors
 *  newStoreRulesForAll over provider[id].options. */
function legacyPlanEntriesForAll(root: Record<string, unknown>, policy: ZcodeRoutePolicy): { routed: LegacyEntry[]; skipped: { id: string; reason: string }[] } {
    const routed: LegacyEntry[] = [];
    const skipped: { id: string; reason: string }[] = [];
    const provider = asRecord(root.provider);
    if (!provider) return { routed, skipped };
    for (const id of Object.keys(provider)) {
        const options = asRecord(asRecord(provider[id])?.options);
        const upstream = options === undefined ? undefined : unwrapBaseUrl(options.baseURL);
        const reason = zcodeEntrySkipReason(id, upstream, upstream !== undefined, "legacy", policy);
        if (reason !== undefined || options === undefined || upstream === undefined) {
            skipped.push({ id, reason: reason ?? "no usable http(s) baseURL — left untouched" });
            continue;
        }
        routed.push({ id, options });
    }
    return { routed, skipped };
}

function applyLegacy(text: string, origin: string, policy: ZcodeRoutePolicy): ZcodeApplyOutcome {
    const root = parseRoot(text, "zcode v2/config.json");
    const wrapped: ZcodeWrappedEntry[] = [];
    const skipped: { id: string; reason: string }[] = [];
    if (policy.route === "all") {
        const selection = legacyPlanEntriesForAll(root, policy);
        for (const { id, options } of selection.routed) {
            const upstream = unwrapBaseUrl(options.baseURL);
            if (upstream === undefined) continue; // filtered above; keeps TS honest
            options.baseURL = `${origin}/bili/${upstream}`;
            wrapped.push({ id, upstream });
        }
        skipped.push(...selection.skipped);
        return { text: serialize(root), wrapped, skipped };
    }
    for (const { id, options } of legacyPlanEntries(root, true)) {
        const upstream = unwrapBaseUrl(options.baseURL) ?? ZCODE_BIGMODEL_ANTHROPIC_UPSTREAM;
        options.baseURL = `${origin}/sigma/${upstream}`;
        wrapped.push({ id, upstream });
    }
    return { text: serialize(root), wrapped, skipped };
}

function assertNewStoreShape(doc: unknown): void {
    const root = asRecord(doc);
    if (!root) throw new Error("zcode provider_config.json must be a JSON object");
    if (root.schemaVersion !== 1) throw new Error(`unsupported provider_config.json schemaVersion: ${String(root.schemaVersion)}`);
    const config = asRecord(root.config);
    if (!config) throw new Error("provider_config.json is missing its config object");
    const rulesField = asRecord(config.providerConfigRules);
    if (rulesField !== undefined && !Array.isArray(rulesField.providerRules)) {
        throw new Error("provider_config.json config.providerConfigRules.providerRules must be an array");
    }
}

interface NewRule {
    readonly id: string;
    readonly api: Record<string, unknown>;
}

/** The providerRules array of a new store, read-only (empty when absent). */
function newRuleArray(root: Record<string, unknown>): unknown[] {
    const rulesField = asRecord(asRecord(root.config)?.providerConfigRules);
    return rulesField && Array.isArray(rulesField.providerRules) ? (rulesField.providerRules as unknown[]) : [];
}

function newPlanRules(root: Record<string, unknown>, createWhenEmpty: boolean): NewRule[] {
    const config = asRecord(root.config);
    if (!config) throw new Error("provider_config.json is missing its config object");
    let rulesField = asRecord(config.providerConfigRules);
    if (!rulesField) {
        if (!createWhenEmpty) return [];
        rulesField = { providerRules: [] };
        config.providerConfigRules = rulesField;
    }
    const rules = Array.isArray(rulesField.providerRules) ? (rulesField.providerRules as unknown[]) : [];
    const found: NewRule[] = [];
    for (const raw of rules) {
        const rule = asRecord(raw);
        if (!rule || typeof rule.providerId !== "string" || !ZCODE_NEW_PLAN_IDS.includes(rule.providerId)) continue;
        const configObj = asRecord(rule.config);
        if (!configObj) continue;
        let api = asRecord(configObj.api);
        if (!api) {
            api = {};
            configObj.api = api;
        }
        found.push({ id: rule.providerId, api });
    }
    if (found.length > 0) return found;
    if (!createWhenEmpty) return [];
    for (const id of ZCODE_NEW_CREATE_IDS) {
        const rule: Record<string, unknown> = { providerId: id, config: { api: {} } };
        rules.push(rule);
        const api = (asRecord(asRecord(rule.config)?.api) ?? {}) as Record<string, unknown>;
        found.push({ id, api });
    }
    return found;
}

/** #1622 route:"all" selection — every provider entry in the store is a
 *  candidate; entries the policy cannot safely wrap are reported, not
 *  silently dropped. Nothing is synthesized and nothing is default-filled:
 *  "all" wraps what exists, exactly like the in-process natives. */
function newStoreRulesForAll(root: Record<string, unknown>, policy: ZcodeRoutePolicy): { routed: NewRule[]; skipped: { id: string; reason: string }[] } {
    const routed: NewRule[] = [];
    const skipped: { id: string; reason: string }[] = [];
    for (const raw of newRuleArray(root)) {
        const rule = asRecord(raw);
        if (!rule || typeof rule.providerId !== "string" || rule.providerId.length === 0) continue;
        const api = asRecord(asRecord(rule.config)?.api);
        const upstream = api === undefined ? undefined : unwrapBaseUrl(api.baseUrl);
        const reason = zcodeEntrySkipReason(rule.providerId, upstream, upstream !== undefined, "new", policy);
        if (reason !== undefined || api === undefined || upstream === undefined) {
            skipped.push({ id: rule.providerId, reason: reason ?? "no usable http(s) baseUrl — left untouched" });
            continue;
        }
        routed.push({ id: rule.providerId, api });
    }
    return { routed, skipped };
}

export interface ZcodeApplyOutcome {
    readonly text: string;
    readonly wrapped: ZcodeWrappedEntry[];
    readonly skipped: readonly { id: string; reason: string }[];
}

function applyNew(text: string, origin: string, policy: ZcodeRoutePolicy): ZcodeApplyOutcome {
    const root = parseRoot(text, "zcode v2/provider_config.json");
    assertNewStoreShape(root);
    const wrapped: ZcodeWrappedEntry[] = [];
    const skipped: { id: string; reason: string }[] = [];
    if (policy.route === "all") {
        for (const { id, api } of newStoreRulesForAll(root, policy).routed) {
            const upstream = unwrapBaseUrl(api.baseUrl);
            if (upstream === undefined) continue; // filtered above; keeps TS honest
            api.baseUrl = `${origin}/bili/${upstream}`;
            wrapped.push({ id, upstream });
        }
        skipped.push(...newStoreRulesForAll(root, policy).skipped);
        return { text: serialize(root), wrapped, skipped };
    }
    for (const { id, api } of newPlanRules(root, true)) {
        const upstream = unwrapBaseUrl(api.baseUrl) ?? ZCODE_BIGMODEL_ANTHROPIC_UPSTREAM;
        api.baseUrl = `${origin}/sigma/${upstream}`;
        wrapped.push({ id, upstream });
    }
    return { text: serialize(root), wrapped, skipped };
}

export function applyZcodeRouting(text: string, kind: ZcodeStoreKind, origin: string, policy: ZcodeRoutePolicy = defaultZcodeRoutePolicy()): ZcodeApplyOutcome {
    return kind === "new" ? applyNew(text, origin, policy) : applyLegacy(text, origin, policy);
}

function stampHeaders(headers: unknown): Record<string, unknown> | undefined {
    const existing = asRecord(headers);
    const next: Record<string, unknown> = existing ? { ...existing } : {};
    next[ZCODE_PLUGIN_HEADER] = ZCODE_AGENT_VALUE;
    return next;
}

function stampLegacy(text: string): string {
    const root = parseRoot(text, "zcode v2/config.json");
    let changed = false;
    const provider = asRecord(root.provider);
    if (provider) {
        // route:"all" may wrap any provider entry, so stamp whatever carries a wrapper.
        for (const id of Object.keys(provider)) {
            const options = asRecord(asRecord(provider[id])?.options);
            if (!options || !WRAPPED_URL_RE.test(String(options.baseURL))) continue;
            const stamped = stampHeaders(options.headers);
            if (stamped) {
                options.headers = stamped;
                changed = true;
            }
        }
    }
    return changed ? serialize(root) : text;
}

function stampNew(text: string): string {
    const root = parseRoot(text, "zcode v2/provider_config.json");
    assertNewStoreShape(root);
    let changed = false;
    const rulesField = asRecord(asRecord(root.config)?.providerConfigRules);
    const rules = rulesField && Array.isArray(rulesField.providerRules) ? (rulesField.providerRules as unknown[]) : [];
    for (const raw of rules) {
        const api = asRecord(asRecord(asRecord(raw)?.config)?.api);
        if (!api || !WRAPPED_URL_RE.test(String(api.baseUrl))) continue;
        const stamped = stampHeaders(api.headers);
        if (stamped) {
            api.headers = stamped;
            changed = true;
        }
    }
    return changed ? serialize(root) : text;
}

export function stampZcodePluginHeader(text: string, kind: ZcodeStoreKind): string {
    return kind === "new" ? stampNew(text) : stampLegacy(text);
}

function unrouteHeaders(headers: unknown): void {
    const existing = asRecord(headers);
    if (existing && Object.prototype.hasOwnProperty.call(existing, ZCODE_PLUGIN_HEADER)) delete existing[ZCODE_PLUGIN_HEADER];
}

function unrouteLegacy(text: string): { text: string; changed: boolean } {
    const root = parseRoot(text, "zcode v2/config.json");
    let changed = false;
    const provider = asRecord(root.provider);
    if (provider) {
        // route:"all" may wrap any provider entry, so strip every wrapper present.
        for (const id of Object.keys(provider)) {
            const options = asRecord(asRecord(provider[id])?.options);
            if (!options || typeof options.baseURL !== "string") continue;
            const match = WRAPPED_URL_RE.exec(options.baseURL);
            if (!match) continue;
            options.baseURL = match[1];
            unrouteHeaders(options.headers);
            changed = true;
        }
    }
    return { text: changed ? serialize(root) : text, changed };
}

function unrouteNew(text: string): { text: string; changed: boolean } {
    const root = parseRoot(text, "zcode v2/provider_config.json");
    assertNewStoreShape(root);
    let changed = false;
    const rulesField = asRecord(asRecord(root.config)?.providerConfigRules);
    const rules = rulesField && Array.isArray(rulesField.providerRules) ? (rulesField.providerRules as unknown[]) : [];
    for (const raw of rules) {
        const api = asRecord(asRecord(asRecord(raw)?.config)?.api);
        if (!api || typeof api.baseUrl !== "string") continue;
        const match = WRAPPED_URL_RE.exec(api.baseUrl);
        if (!match) continue;
        api.baseUrl = match[1];
        unrouteHeaders(api.headers);
        changed = true;
    }
    return { text: changed ? serialize(root) : text, changed };
}

export function unrouteZcodeText(text: string, kind: ZcodeStoreKind): { text: string; changed: boolean } {
    return kind === "new" ? unrouteNew(text) : unrouteLegacy(text);
}

/** Read-only inspection for status reporting: which store exists and which
 *  entries currently route through a sigma origin. */
export function inspectZcodeRouting(dataDir: string, env: NodeJS.ProcessEnv = process.env): { kind: ZcodeStoreKind; file: string; wrapped: ZcodeWrappedEntry[] } | undefined {
    const { kind, file } = detectZcodeStore(dataDir, env);
    let text: string;
    try {
        text = fs.readFileSync(file, "utf8");
    } catch {
        return undefined;
    }
    let doc: unknown;
    try {
        doc = JSON.parse(text);
    } catch {
        return undefined;
    }
    if (kind === "new") {
        const root = asRecord(doc);
        if (!root) return undefined;
        try {
            assertNewStoreShape(root);
        } catch {
            return undefined;
        }
        const wrapped: ZcodeWrappedEntry[] = [];
        for (const raw of newRuleArray(root)) {
            const rule = asRecord(raw);
            if (!rule || typeof rule.providerId !== "string" || rule.providerId.length === 0) continue;
            const baseUrl = asRecord(asRecord(rule.config)?.api)?.baseUrl;
            const match = typeof baseUrl === "string" ? WRAPPED_URL_RE.exec(baseUrl) : undefined;
            if (match) wrapped.push({ id: rule.providerId, upstream: match[1] });
        }
        return { kind, file, wrapped };
    }
    const root = asRecord(doc);
    const provider = root ? asRecord(root.provider) : undefined;
    if (!provider) return undefined;
    const wrapped: ZcodeWrappedEntry[] = [];
    for (const id of Object.keys(provider)) {
        const baseUrl = asRecord(asRecord(provider[id])?.options)?.baseURL;
        const match = typeof baseUrl === "string" ? WRAPPED_URL_RE.exec(baseUrl) : undefined;
        if (match) wrapped.push({ id, upstream: match[1] });
    }
    return { kind, file, wrapped };
}

/** #1623: the origin bili currently routes through, read back from the
 *  managed /bili/ wrappers — undefined when no entry carries one (direct).
 *  Drift repair and exit handoff use it to decide whether the shared store
 *  points at a live instance, a dead one, or at us. */
export function detectCurrentZcodeOrigin(dataDir: string, env: NodeJS.ProcessEnv = process.env): string | undefined {
    const { kind, file } = detectZcodeStore(dataDir, env);
    let text: string;
    try {
        text = fs.readFileSync(file, "utf8");
    } catch {
        return undefined;
    }
    let doc: unknown;
    try {
        doc = JSON.parse(text);
    } catch {
        return undefined;
    }
    const urls: string[] = [];
    if (kind === "new") {
        const rulesField = asRecord(asRecord(asRecord(doc)?.config)?.providerConfigRules);
        const rules = rulesField && Array.isArray(rulesField.providerRules) ? (rulesField.providerRules as unknown[]) : [];
        for (const raw of rules) {
            const api = asRecord(asRecord(asRecord(raw)?.config)?.api);
            if (api && typeof api.baseUrl === "string") urls.push(api.baseUrl);
        }
    } else {
        const provider = asRecord(asRecord(doc)?.provider);
        if (!provider) return undefined;
        for (const value of Object.values(provider)) {
            const options = asRecord(asRecord(value)?.options);
            if (options && typeof options.baseURL === "string") urls.push(options.baseURL);
        }
    }
    for (const url of urls) {
        if (WRAPPED_URL_RE.test(url)) return url.slice(0, url.indexOf("/bili/"));
    }
    return undefined;
}
